### ISSUE TITLE
[Possible Feature] Add support for CW2 Attribute Plugins

### ISSUE THREAD

**Issue by SoulBlast35** [nosoop/SM-TFCW3toX#2]
I know this might be a bit outside the scope for this plugin, but would it be possible to support plugins designed for CW2 like zethax's attributes?

**Comment by nosoop** [comment]
If I recall correctly, the core issue with trying to have CW2 attributes in CWX is that they don't offer any way to "reset" the state of attributes / players, and leave that to plugins cleaning up after themselves with hooks on spawn / resupply events.  The assumptions that were previously made no longer hold true post-Gun Mettle mainly due to weapon pickups, and also the ability to change loadout presets on touching resupply.

I feel like there were other reasons when I was thinking about this back then, but that's all I can think of now.

Beyond that constraint (see: restricting weapon changes only to spawn) I think it's doable, but not something I'm interested in pursuing.  You'd be better off making the effort to port CW2 attributes you really want to CW3 format since they share more similarities with each other than they do CAF / native.  (As long as you implement the reset handling as well, of course.)
